/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the_wall;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
     
/**
 *
 * @author Romero
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        File n=new File("./wall.PNG");
        Image img=Toolkit.getDefaultToolkit().createImage(n.getPath()).getScaledInstance(254, 384, 0);
        poster.setIcon(new ImageIcon(img));
        File archivo = null;
        try {
            archivo = new File("./deportados.trump");
            FileInputStream entrada = new FileInputStream(archivo);
            ObjectInputStream objeto = new ObjectInputStream(entrada);
            Mexicano temp;
            DefaultComboBoxModel modelo = (DefaultComboBoxModel)this.cbx_revision.getModel();
            try {
                while((temp = (Mexicano)objeto.readObject()) != null){
                lista.add(temp);
                modelo.addElement(temp);
                }
            } catch (EOFException e) {
            }
            finally{
            
                objeto.close();
                entrada.close();
            
            }
            this.cbx_revision.setModel(modelo);
        } catch (Exception ex)
        {
            ex.printStackTrace();
        }
        
        Panels.add(Pasajero1);
        Panels.add(Pasajero2);
        Panels.add(Pasajero3);
        Panels.add(Pasajero4);
        Panels.add(Pasajero5);
        Panels.add(Pasajero6);
        Panels.add(Pasajero7);
        Panels.add(Pasajero8);
        Panels.add(Pasajero9);
        Panels.add(Pasajero10);
        Panels.add(Pasajero11);
        Panels.add(Pasajero12);
        Panels.add(Pasajero13);
        Panels.add(Pasajero14);
        Panels.add(Pasajero15);
        Panels.add(Pasajero16);
        Panels.add(Pasajero17);
        Panels.add(Pasajero18);
        Panels.add(Pasajero19);
        Panels.add(Pasajero20);
        Panels.add(Pasajero21);
        Panels.add(Pasajero22);
        Panels.add(Pasajero23);
        Panels.add(Pasajero24);
        Panels.add(Pasajero25);
        Panels.add(Pasajero26);
        Panels.add(Pasajero27);
        Panels.add(Pasajero28);
        Panels.add(Pasajero29);
        Panels.add(Pasajero30);
        Panels.add(Pasajero31);
        Panels.add(Pasajero32);
        Panels.add(Pasajero33);
        Panels.add(Pasajero34);
        Panels.add(Pasajero35);
        Panels.add(Pasajero36);
        Panels.add(Pasajero37);
        Panels.add(Pasajero38);
        Panels.add(Pasajero39);
        Panels.add(Pasajero40);
        Panels.add(Pasajero41);
        Panels.add(Pasajero42);
        Panels.add(Pasajero43);
        Panels.add(Pasajero44);
        Panels.add(Pasajero45);
        Panels.add(Pasajero46);
        Panels.add(Pasajero47);
        Panels.add(Pasajero48);
        Panels.add(Pasajero49);
        Panels.add(Pasajero50);
        
        Labels.add(Avion1);
        Labels.add(Avion2);
        Labels.add(Avion3);
        Labels.add(Avion4);
        Labels.add(Avion5);
        Labels.add(Avion6);
        Labels.add(Avion7);
        Labels.add(Avion8);
        Labels.add(Avion9);
        Labels.add(Avion10);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JDialog();
        tf_nation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_countre_dep = new javax.swing.JTextField();
        cb_race = new javax.swing.JComboBox<>();
        jdc_birth = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Aviones = new javax.swing.JDialog();
        Avion1 = new javax.swing.JLabel();
        Pasajero1 = new javax.swing.JPanel();
        Pasajero2 = new javax.swing.JPanel();
        Pasajero3 = new javax.swing.JPanel();
        Pasajero4 = new javax.swing.JPanel();
        Pasajero5 = new javax.swing.JPanel();
        Avion2 = new javax.swing.JLabel();
        Pasajero6 = new javax.swing.JPanel();
        Pasajero7 = new javax.swing.JPanel();
        Pasajero8 = new javax.swing.JPanel();
        Pasajero9 = new javax.swing.JPanel();
        Pasajero10 = new javax.swing.JPanel();
        Avion3 = new javax.swing.JLabel();
        Pasajero11 = new javax.swing.JPanel();
        Pasajero12 = new javax.swing.JPanel();
        Pasajero13 = new javax.swing.JPanel();
        Pasajero14 = new javax.swing.JPanel();
        Pasajero15 = new javax.swing.JPanel();
        Avion4 = new javax.swing.JLabel();
        Pasajero16 = new javax.swing.JPanel();
        Pasajero17 = new javax.swing.JPanel();
        Pasajero18 = new javax.swing.JPanel();
        Pasajero19 = new javax.swing.JPanel();
        Pasajero20 = new javax.swing.JPanel();
        Avion5 = new javax.swing.JLabel();
        Pasajero21 = new javax.swing.JPanel();
        Pasajero22 = new javax.swing.JPanel();
        Pasajero23 = new javax.swing.JPanel();
        Pasajero24 = new javax.swing.JPanel();
        Pasajero25 = new javax.swing.JPanel();
        Avion6 = new javax.swing.JLabel();
        Pasajero26 = new javax.swing.JPanel();
        Pasajero27 = new javax.swing.JPanel();
        Pasajero28 = new javax.swing.JPanel();
        Pasajero29 = new javax.swing.JPanel();
        Pasajero30 = new javax.swing.JPanel();
        Avion7 = new javax.swing.JLabel();
        Pasajero31 = new javax.swing.JPanel();
        Pasajero32 = new javax.swing.JPanel();
        Pasajero33 = new javax.swing.JPanel();
        Pasajero34 = new javax.swing.JPanel();
        Pasajero35 = new javax.swing.JPanel();
        Avion8 = new javax.swing.JLabel();
        Pasajero36 = new javax.swing.JPanel();
        Pasajero37 = new javax.swing.JPanel();
        Pasajero38 = new javax.swing.JPanel();
        Pasajero39 = new javax.swing.JPanel();
        Pasajero40 = new javax.swing.JPanel();
        Avion9 = new javax.swing.JLabel();
        Pasajero41 = new javax.swing.JPanel();
        Pasajero42 = new javax.swing.JPanel();
        Pasajero43 = new javax.swing.JPanel();
        Pasajero44 = new javax.swing.JPanel();
        Pasajero45 = new javax.swing.JPanel();
        Avion10 = new javax.swing.JLabel();
        Pasajero46 = new javax.swing.JPanel();
        Pasajero47 = new javax.swing.JPanel();
        Pasajero48 = new javax.swing.JPanel();
        Pasajero49 = new javax.swing.JPanel();
        Pasajero50 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        poster = new javax.swing.JLabel();
        cbx_revision = new javax.swing.JComboBox<>();

        tf_nation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Country of deportation");

        cb_race.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mexican", "latino", "cubano", "musllm", "chinese", "black", "vulcan" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Name");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Nationality");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Birthday");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Race or ethnic group");

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel2.setText("Registro");

        jButton1.setText("Deportar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7))
                        .addGap(55, 55, 55)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_name)
                            .addComponent(tf_nation)
                            .addComponent(tf_countre_dep)
                            .addComponent(cb_race, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdc_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(173, 173, 173))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(176, 176, 176)))))
                .addGap(82, 82, 82))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jdc_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_race, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_countre_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        Aviones.setIconImage(null);

        Pasajero1.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero1.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero1Layout = new javax.swing.GroupLayout(Pasajero1);
        Pasajero1.setLayout(Pasajero1Layout);
        Pasajero1Layout.setHorizontalGroup(
            Pasajero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero1Layout.setVerticalGroup(
            Pasajero1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero2.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero2.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero2Layout = new javax.swing.GroupLayout(Pasajero2);
        Pasajero2.setLayout(Pasajero2Layout);
        Pasajero2Layout.setHorizontalGroup(
            Pasajero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero2Layout.setVerticalGroup(
            Pasajero2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero3.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero3.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero3Layout = new javax.swing.GroupLayout(Pasajero3);
        Pasajero3.setLayout(Pasajero3Layout);
        Pasajero3Layout.setHorizontalGroup(
            Pasajero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero3Layout.setVerticalGroup(
            Pasajero3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero4.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero4.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero4Layout = new javax.swing.GroupLayout(Pasajero4);
        Pasajero4.setLayout(Pasajero4Layout);
        Pasajero4Layout.setHorizontalGroup(
            Pasajero4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero4Layout.setVerticalGroup(
            Pasajero4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero5.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero5.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero5Layout = new javax.swing.GroupLayout(Pasajero5);
        Pasajero5.setLayout(Pasajero5Layout);
        Pasajero5Layout.setHorizontalGroup(
            Pasajero5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero5Layout.setVerticalGroup(
            Pasajero5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero6.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero6.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero6Layout = new javax.swing.GroupLayout(Pasajero6);
        Pasajero6.setLayout(Pasajero6Layout);
        Pasajero6Layout.setHorizontalGroup(
            Pasajero6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero6Layout.setVerticalGroup(
            Pasajero6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero7.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero7.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero7Layout = new javax.swing.GroupLayout(Pasajero7);
        Pasajero7.setLayout(Pasajero7Layout);
        Pasajero7Layout.setHorizontalGroup(
            Pasajero7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero7Layout.setVerticalGroup(
            Pasajero7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero8.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero8.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero8Layout = new javax.swing.GroupLayout(Pasajero8);
        Pasajero8.setLayout(Pasajero8Layout);
        Pasajero8Layout.setHorizontalGroup(
            Pasajero8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero8Layout.setVerticalGroup(
            Pasajero8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero9.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero9.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero9Layout = new javax.swing.GroupLayout(Pasajero9);
        Pasajero9.setLayout(Pasajero9Layout);
        Pasajero9Layout.setHorizontalGroup(
            Pasajero9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero9Layout.setVerticalGroup(
            Pasajero9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero10.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero10.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero10Layout = new javax.swing.GroupLayout(Pasajero10);
        Pasajero10.setLayout(Pasajero10Layout);
        Pasajero10Layout.setHorizontalGroup(
            Pasajero10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero10Layout.setVerticalGroup(
            Pasajero10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero11.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero11.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero11Layout = new javax.swing.GroupLayout(Pasajero11);
        Pasajero11.setLayout(Pasajero11Layout);
        Pasajero11Layout.setHorizontalGroup(
            Pasajero11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero11Layout.setVerticalGroup(
            Pasajero11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero12.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero12.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero12Layout = new javax.swing.GroupLayout(Pasajero12);
        Pasajero12.setLayout(Pasajero12Layout);
        Pasajero12Layout.setHorizontalGroup(
            Pasajero12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero12Layout.setVerticalGroup(
            Pasajero12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero13.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero13.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero13Layout = new javax.swing.GroupLayout(Pasajero13);
        Pasajero13.setLayout(Pasajero13Layout);
        Pasajero13Layout.setHorizontalGroup(
            Pasajero13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero13Layout.setVerticalGroup(
            Pasajero13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero14.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero14.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero14Layout = new javax.swing.GroupLayout(Pasajero14);
        Pasajero14.setLayout(Pasajero14Layout);
        Pasajero14Layout.setHorizontalGroup(
            Pasajero14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero14Layout.setVerticalGroup(
            Pasajero14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero15.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero15.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero15Layout = new javax.swing.GroupLayout(Pasajero15);
        Pasajero15.setLayout(Pasajero15Layout);
        Pasajero15Layout.setHorizontalGroup(
            Pasajero15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero15Layout.setVerticalGroup(
            Pasajero15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero16.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero16.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero16Layout = new javax.swing.GroupLayout(Pasajero16);
        Pasajero16.setLayout(Pasajero16Layout);
        Pasajero16Layout.setHorizontalGroup(
            Pasajero16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero16Layout.setVerticalGroup(
            Pasajero16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero17.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero17.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero17Layout = new javax.swing.GroupLayout(Pasajero17);
        Pasajero17.setLayout(Pasajero17Layout);
        Pasajero17Layout.setHorizontalGroup(
            Pasajero17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero17Layout.setVerticalGroup(
            Pasajero17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero18.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero18.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero18Layout = new javax.swing.GroupLayout(Pasajero18);
        Pasajero18.setLayout(Pasajero18Layout);
        Pasajero18Layout.setHorizontalGroup(
            Pasajero18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero18Layout.setVerticalGroup(
            Pasajero18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero19.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero19.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero19Layout = new javax.swing.GroupLayout(Pasajero19);
        Pasajero19.setLayout(Pasajero19Layout);
        Pasajero19Layout.setHorizontalGroup(
            Pasajero19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero19Layout.setVerticalGroup(
            Pasajero19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero20.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero20.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero20Layout = new javax.swing.GroupLayout(Pasajero20);
        Pasajero20.setLayout(Pasajero20Layout);
        Pasajero20Layout.setHorizontalGroup(
            Pasajero20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero20Layout.setVerticalGroup(
            Pasajero20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero21.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero21.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero21Layout = new javax.swing.GroupLayout(Pasajero21);
        Pasajero21.setLayout(Pasajero21Layout);
        Pasajero21Layout.setHorizontalGroup(
            Pasajero21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero21Layout.setVerticalGroup(
            Pasajero21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero22.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero22.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero22Layout = new javax.swing.GroupLayout(Pasajero22);
        Pasajero22.setLayout(Pasajero22Layout);
        Pasajero22Layout.setHorizontalGroup(
            Pasajero22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero22Layout.setVerticalGroup(
            Pasajero22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero23.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero23.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero23Layout = new javax.swing.GroupLayout(Pasajero23);
        Pasajero23.setLayout(Pasajero23Layout);
        Pasajero23Layout.setHorizontalGroup(
            Pasajero23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero23Layout.setVerticalGroup(
            Pasajero23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero24.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero24.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero24Layout = new javax.swing.GroupLayout(Pasajero24);
        Pasajero24.setLayout(Pasajero24Layout);
        Pasajero24Layout.setHorizontalGroup(
            Pasajero24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero24Layout.setVerticalGroup(
            Pasajero24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero25.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero25.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero25Layout = new javax.swing.GroupLayout(Pasajero25);
        Pasajero25.setLayout(Pasajero25Layout);
        Pasajero25Layout.setHorizontalGroup(
            Pasajero25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero25Layout.setVerticalGroup(
            Pasajero25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero26.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero26.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero26Layout = new javax.swing.GroupLayout(Pasajero26);
        Pasajero26.setLayout(Pasajero26Layout);
        Pasajero26Layout.setHorizontalGroup(
            Pasajero26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero26Layout.setVerticalGroup(
            Pasajero26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero27.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero27.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero27Layout = new javax.swing.GroupLayout(Pasajero27);
        Pasajero27.setLayout(Pasajero27Layout);
        Pasajero27Layout.setHorizontalGroup(
            Pasajero27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero27Layout.setVerticalGroup(
            Pasajero27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero28.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero28.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero28Layout = new javax.swing.GroupLayout(Pasajero28);
        Pasajero28.setLayout(Pasajero28Layout);
        Pasajero28Layout.setHorizontalGroup(
            Pasajero28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero28Layout.setVerticalGroup(
            Pasajero28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero29.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero29.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero29Layout = new javax.swing.GroupLayout(Pasajero29);
        Pasajero29.setLayout(Pasajero29Layout);
        Pasajero29Layout.setHorizontalGroup(
            Pasajero29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero29Layout.setVerticalGroup(
            Pasajero29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero30.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero30.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero30Layout = new javax.swing.GroupLayout(Pasajero30);
        Pasajero30.setLayout(Pasajero30Layout);
        Pasajero30Layout.setHorizontalGroup(
            Pasajero30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero30Layout.setVerticalGroup(
            Pasajero30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero31.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero31.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero31Layout = new javax.swing.GroupLayout(Pasajero31);
        Pasajero31.setLayout(Pasajero31Layout);
        Pasajero31Layout.setHorizontalGroup(
            Pasajero31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero31Layout.setVerticalGroup(
            Pasajero31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero32.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero32.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero32Layout = new javax.swing.GroupLayout(Pasajero32);
        Pasajero32.setLayout(Pasajero32Layout);
        Pasajero32Layout.setHorizontalGroup(
            Pasajero32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero32Layout.setVerticalGroup(
            Pasajero32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero33.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero33.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero33Layout = new javax.swing.GroupLayout(Pasajero33);
        Pasajero33.setLayout(Pasajero33Layout);
        Pasajero33Layout.setHorizontalGroup(
            Pasajero33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero33Layout.setVerticalGroup(
            Pasajero33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero34.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero34.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero34Layout = new javax.swing.GroupLayout(Pasajero34);
        Pasajero34.setLayout(Pasajero34Layout);
        Pasajero34Layout.setHorizontalGroup(
            Pasajero34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero34Layout.setVerticalGroup(
            Pasajero34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero35.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero35.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero35Layout = new javax.swing.GroupLayout(Pasajero35);
        Pasajero35.setLayout(Pasajero35Layout);
        Pasajero35Layout.setHorizontalGroup(
            Pasajero35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero35Layout.setVerticalGroup(
            Pasajero35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero36.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero36.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero36Layout = new javax.swing.GroupLayout(Pasajero36);
        Pasajero36.setLayout(Pasajero36Layout);
        Pasajero36Layout.setHorizontalGroup(
            Pasajero36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero36Layout.setVerticalGroup(
            Pasajero36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero37.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero37.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero37Layout = new javax.swing.GroupLayout(Pasajero37);
        Pasajero37.setLayout(Pasajero37Layout);
        Pasajero37Layout.setHorizontalGroup(
            Pasajero37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero37Layout.setVerticalGroup(
            Pasajero37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero38.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero38.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero38Layout = new javax.swing.GroupLayout(Pasajero38);
        Pasajero38.setLayout(Pasajero38Layout);
        Pasajero38Layout.setHorizontalGroup(
            Pasajero38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero38Layout.setVerticalGroup(
            Pasajero38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero39.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero39.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero39Layout = new javax.swing.GroupLayout(Pasajero39);
        Pasajero39.setLayout(Pasajero39Layout);
        Pasajero39Layout.setHorizontalGroup(
            Pasajero39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero39Layout.setVerticalGroup(
            Pasajero39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero40.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero40.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero40Layout = new javax.swing.GroupLayout(Pasajero40);
        Pasajero40.setLayout(Pasajero40Layout);
        Pasajero40Layout.setHorizontalGroup(
            Pasajero40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero40Layout.setVerticalGroup(
            Pasajero40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero41.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero41.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero41Layout = new javax.swing.GroupLayout(Pasajero41);
        Pasajero41.setLayout(Pasajero41Layout);
        Pasajero41Layout.setHorizontalGroup(
            Pasajero41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero41Layout.setVerticalGroup(
            Pasajero41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero42.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero42.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero42Layout = new javax.swing.GroupLayout(Pasajero42);
        Pasajero42.setLayout(Pasajero42Layout);
        Pasajero42Layout.setHorizontalGroup(
            Pasajero42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero42Layout.setVerticalGroup(
            Pasajero42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero43.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero43.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero43Layout = new javax.swing.GroupLayout(Pasajero43);
        Pasajero43.setLayout(Pasajero43Layout);
        Pasajero43Layout.setHorizontalGroup(
            Pasajero43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero43Layout.setVerticalGroup(
            Pasajero43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero44.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero44.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero44Layout = new javax.swing.GroupLayout(Pasajero44);
        Pasajero44.setLayout(Pasajero44Layout);
        Pasajero44Layout.setHorizontalGroup(
            Pasajero44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero44Layout.setVerticalGroup(
            Pasajero44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero45.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero45.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero45Layout = new javax.swing.GroupLayout(Pasajero45);
        Pasajero45.setLayout(Pasajero45Layout);
        Pasajero45Layout.setHorizontalGroup(
            Pasajero45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero45Layout.setVerticalGroup(
            Pasajero45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero46.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero46.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero46Layout = new javax.swing.GroupLayout(Pasajero46);
        Pasajero46.setLayout(Pasajero46Layout);
        Pasajero46Layout.setHorizontalGroup(
            Pasajero46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero46Layout.setVerticalGroup(
            Pasajero46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero47.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero47.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero47Layout = new javax.swing.GroupLayout(Pasajero47);
        Pasajero47.setLayout(Pasajero47Layout);
        Pasajero47Layout.setHorizontalGroup(
            Pasajero47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero47Layout.setVerticalGroup(
            Pasajero47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero48.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero48.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero48Layout = new javax.swing.GroupLayout(Pasajero48);
        Pasajero48.setLayout(Pasajero48Layout);
        Pasajero48Layout.setHorizontalGroup(
            Pasajero48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero48Layout.setVerticalGroup(
            Pasajero48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero49.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero49.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero49Layout = new javax.swing.GroupLayout(Pasajero49);
        Pasajero49.setLayout(Pasajero49Layout);
        Pasajero49Layout.setHorizontalGroup(
            Pasajero49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero49Layout.setVerticalGroup(
            Pasajero49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        Pasajero50.setBackground(new java.awt.Color(255, 0, 0));
        Pasajero50.setPreferredSize(new java.awt.Dimension(50, 33));

        javax.swing.GroupLayout Pasajero50Layout = new javax.swing.GroupLayout(Pasajero50);
        Pasajero50.setLayout(Pasajero50Layout);
        Pasajero50Layout.setHorizontalGroup(
            Pasajero50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        Pasajero50Layout.setVerticalGroup(
            Pasajero50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jButton4.setText("Initiate Process of Deportation!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AvionesLayout = new javax.swing.GroupLayout(Aviones.getContentPane());
        Aviones.getContentPane().setLayout(AvionesLayout);
        AvionesLayout.setHorizontalGroup(
            AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvionesLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion6, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion7, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion8, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion9, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion10, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pasajero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pasajero10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AvionesLayout.createSequentialGroup()
                                .addComponent(Pasajero21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pasajero25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Avion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AvionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(762, 762, 762))
        );
        AvionesLayout.setVerticalGroup(
            AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AvionesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion10, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AvionesLayout.createSequentialGroup()
                        .addComponent(Avion6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AvionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pasajero26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pasajero30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("THE WALL");

        jButton2.setText("Registro");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Deportacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cbx_revision, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jButton3)))
                        .addGap(210, 210, 210))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poster, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(cbx_revision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nationActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.Registro.pack();
        this.Registro.setModal(true);
        this.setLocationRelativeTo(this);
        this.Registro.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        File n=new File("./Avion.jpg");
        Image img=Toolkit.getDefaultToolkit().createImage(n.getPath()).getScaledInstance(316, 149, 0);
        
        Avion1.setIcon(new ImageIcon(img));
        Avion2.setIcon(new ImageIcon(img));
        Avion3.setIcon(new ImageIcon(img));
        Avion4.setIcon(new ImageIcon(img));
        Avion5.setIcon(new ImageIcon(img));
        Avion6.setIcon(new ImageIcon(img));
        Avion7.setIcon(new ImageIcon(img));
        Avion8.setIcon(new ImageIcon(img));
        Avion9.setIcon(new ImageIcon(img));
        Avion10.setIcon(new ImageIcon(img));
        
        this.Aviones.setModal(true);
        this.Aviones.pack();
        this.Aviones.setLocationRelativeTo(this);
        this.Aviones.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Mexicano p = new Mexicano(tf_name.getText(),this.tf_nation.getText(),this.jdc_birth.toString(),this.cb_race.toString(),this.tf_countre_dep.getText(),false);
        File archivo = new File("./deportados.trump");;

        try {
            if (!archivo.exists()) {
                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto = new ObjectOutputStream(salida);
                objeto.writeObject(p);
                objeto.flush();
                objeto.close();
                salida.close();
            } else {
                FileInputStream entrada = new FileInputStream(archivo);
                ObjectInputStream objeto = new ObjectInputStream(entrada);
                Mexicano temp;
                ArrayList<Mexicano> deporta = new ArrayList<Mexicano>();
                try {
                    while ((temp = (Mexicano) objeto.readObject()) != null) {
                        deporta.add(temp);
                    }
                } catch (EOFException e) {
                    //fin del archivo
                }
                objeto.close();
                entrada.close();
                deporta.add(p);

                FileOutputStream salida = new FileOutputStream(archivo);
                ObjectOutputStream objeto2 = new ObjectOutputStream(salida);

                for (Mexicano t : deporta) {
                    objeto2.writeObject(t);
                }
                objeto2.flush();
                objeto2.close();
                salida.close();
            }
            lista.add(p);
            tf_name.setText("");
            tf_nation.setText("");
            tf_countre_dep.setText("");
            JOptionPane.showMessageDialog(this, "El ilegal fue registrado exitosamente");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        int contadorP = 0;
        int contadorL = 0;
        
        /*ArrayList<Mexicano> temp = new ArrayList();
        
        for (int i = 0; i < lista.size(); i++) {
            if (lista.get(i).Departed == false) {
                temp.add(lista.get(i));
                lista.get(i).setDeparted(true);
            }
        }*/
        
        (new HiloP(Panels, Labels, lista, contadorP,contadorL)).start();
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avion1;
    private javax.swing.JLabel Avion10;
    private javax.swing.JLabel Avion2;
    private javax.swing.JLabel Avion3;
    private javax.swing.JLabel Avion4;
    private javax.swing.JLabel Avion5;
    private javax.swing.JLabel Avion6;
    private javax.swing.JLabel Avion7;
    private javax.swing.JLabel Avion8;
    private javax.swing.JLabel Avion9;
    private javax.swing.JDialog Aviones;
    private javax.swing.JPanel Pasajero1;
    private javax.swing.JPanel Pasajero10;
    private javax.swing.JPanel Pasajero11;
    private javax.swing.JPanel Pasajero12;
    private javax.swing.JPanel Pasajero13;
    private javax.swing.JPanel Pasajero14;
    private javax.swing.JPanel Pasajero15;
    private javax.swing.JPanel Pasajero16;
    private javax.swing.JPanel Pasajero17;
    private javax.swing.JPanel Pasajero18;
    private javax.swing.JPanel Pasajero19;
    private javax.swing.JPanel Pasajero2;
    private javax.swing.JPanel Pasajero20;
    private javax.swing.JPanel Pasajero21;
    private javax.swing.JPanel Pasajero22;
    private javax.swing.JPanel Pasajero23;
    private javax.swing.JPanel Pasajero24;
    private javax.swing.JPanel Pasajero25;
    private javax.swing.JPanel Pasajero26;
    private javax.swing.JPanel Pasajero27;
    private javax.swing.JPanel Pasajero28;
    private javax.swing.JPanel Pasajero29;
    private javax.swing.JPanel Pasajero3;
    private javax.swing.JPanel Pasajero30;
    private javax.swing.JPanel Pasajero31;
    private javax.swing.JPanel Pasajero32;
    private javax.swing.JPanel Pasajero33;
    private javax.swing.JPanel Pasajero34;
    private javax.swing.JPanel Pasajero35;
    private javax.swing.JPanel Pasajero36;
    private javax.swing.JPanel Pasajero37;
    private javax.swing.JPanel Pasajero38;
    private javax.swing.JPanel Pasajero39;
    private javax.swing.JPanel Pasajero4;
    private javax.swing.JPanel Pasajero40;
    private javax.swing.JPanel Pasajero41;
    private javax.swing.JPanel Pasajero42;
    private javax.swing.JPanel Pasajero43;
    private javax.swing.JPanel Pasajero44;
    private javax.swing.JPanel Pasajero45;
    private javax.swing.JPanel Pasajero46;
    private javax.swing.JPanel Pasajero47;
    private javax.swing.JPanel Pasajero48;
    private javax.swing.JPanel Pasajero49;
    private javax.swing.JPanel Pasajero5;
    private javax.swing.JPanel Pasajero50;
    private javax.swing.JPanel Pasajero6;
    private javax.swing.JPanel Pasajero7;
    private javax.swing.JPanel Pasajero8;
    private javax.swing.JPanel Pasajero9;
    private javax.swing.JDialog Registro;
    private javax.swing.JComboBox<String> cb_race;
    private javax.swing.JComboBox<String> cbx_revision;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdc_birth;
    private javax.swing.JLabel poster;
    private javax.swing.JTextField tf_countre_dep;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_nation;
    // End of variables declaration//GEN-END:variables
    ArrayList <Mexicano> lista=new ArrayList();
    ArrayList<JPanel> Panels = new ArrayList();
    ArrayList<JLabel> Labels = new ArrayList();
}
